/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.yellowcab;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class StatusMessage implements org.apache.thrift.TBase<StatusMessage, StatusMessage._Fields>, java.io.Serializable, Cloneable, Comparable<StatusMessage> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("StatusMessage");

  private static final org.apache.thrift.protocol.TField MESSAGE_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("messageStatus", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField BODY_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("bodyType", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new StatusMessageStandardSchemeFactory());
    schemes.put(TupleScheme.class, new StatusMessageTupleSchemeFactory());
  }

  public MessageStatus messageStatus; // required
  /**
   * 
   * @see MessageBodyType
   */
  public MessageBodyType bodyType; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MESSAGE_STATUS((short)1, "messageStatus"),
    /**
     * 
     * @see MessageBodyType
     */
    BODY_TYPE((short)2, "bodyType");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MESSAGE_STATUS
          return MESSAGE_STATUS;
        case 2: // BODY_TYPE
          return BODY_TYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MESSAGE_STATUS, new org.apache.thrift.meta_data.FieldMetaData("messageStatus", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, MessageStatus.class)));
    tmpMap.put(_Fields.BODY_TYPE, new org.apache.thrift.meta_data.FieldMetaData("bodyType", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, MessageBodyType.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(StatusMessage.class, metaDataMap);
  }

  public StatusMessage() {
  }

  public StatusMessage(
    MessageStatus messageStatus,
    MessageBodyType bodyType)
  {
    this();
    this.messageStatus = messageStatus;
    this.bodyType = bodyType;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public StatusMessage(StatusMessage other) {
    if (other.isSetMessageStatus()) {
      this.messageStatus = new MessageStatus(other.messageStatus);
    }
    if (other.isSetBodyType()) {
      this.bodyType = other.bodyType;
    }
  }

  public StatusMessage deepCopy() {
    return new StatusMessage(this);
  }

  @Override
  public void clear() {
    this.messageStatus = null;
    this.bodyType = null;
  }

  public MessageStatus getMessageStatus() {
    return this.messageStatus;
  }

  public StatusMessage setMessageStatus(MessageStatus messageStatus) {
    this.messageStatus = messageStatus;
    return this;
  }

  public void unsetMessageStatus() {
    this.messageStatus = null;
  }

  /** Returns true if field messageStatus is set (has been assigned a value) and false otherwise */
  public boolean isSetMessageStatus() {
    return this.messageStatus != null;
  }

  public void setMessageStatusIsSet(boolean value) {
    if (!value) {
      this.messageStatus = null;
    }
  }

  /**
   * 
   * @see MessageBodyType
   */
  public MessageBodyType getBodyType() {
    return this.bodyType;
  }

  /**
   * 
   * @see MessageBodyType
   */
  public StatusMessage setBodyType(MessageBodyType bodyType) {
    this.bodyType = bodyType;
    return this;
  }

  public void unsetBodyType() {
    this.bodyType = null;
  }

  /** Returns true if field bodyType is set (has been assigned a value) and false otherwise */
  public boolean isSetBodyType() {
    return this.bodyType != null;
  }

  public void setBodyTypeIsSet(boolean value) {
    if (!value) {
      this.bodyType = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MESSAGE_STATUS:
      if (value == null) {
        unsetMessageStatus();
      } else {
        setMessageStatus((MessageStatus)value);
      }
      break;

    case BODY_TYPE:
      if (value == null) {
        unsetBodyType();
      } else {
        setBodyType((MessageBodyType)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MESSAGE_STATUS:
      return getMessageStatus();

    case BODY_TYPE:
      return getBodyType();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MESSAGE_STATUS:
      return isSetMessageStatus();
    case BODY_TYPE:
      return isSetBodyType();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof StatusMessage)
      return this.equals((StatusMessage)that);
    return false;
  }

  public boolean equals(StatusMessage that) {
    if (that == null)
      return false;

    boolean this_present_messageStatus = true && this.isSetMessageStatus();
    boolean that_present_messageStatus = true && that.isSetMessageStatus();
    if (this_present_messageStatus || that_present_messageStatus) {
      if (!(this_present_messageStatus && that_present_messageStatus))
        return false;
      if (!this.messageStatus.equals(that.messageStatus))
        return false;
    }

    boolean this_present_bodyType = true && this.isSetBodyType();
    boolean that_present_bodyType = true && that.isSetBodyType();
    if (this_present_bodyType || that_present_bodyType) {
      if (!(this_present_bodyType && that_present_bodyType))
        return false;
      if (!this.bodyType.equals(that.bodyType))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(StatusMessage other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMessageStatus()).compareTo(other.isSetMessageStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMessageStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.messageStatus, other.messageStatus);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBodyType()).compareTo(other.isSetBodyType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBodyType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bodyType, other.bodyType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("StatusMessage(");
    boolean first = true;

    sb.append("messageStatus:");
    if (this.messageStatus == null) {
      sb.append("null");
    } else {
      sb.append(this.messageStatus);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("bodyType:");
    if (this.bodyType == null) {
      sb.append("null");
    } else {
      sb.append(this.bodyType);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (messageStatus == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'messageStatus' was not present! Struct: " + toString());
    }
    if (bodyType == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'bodyType' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (messageStatus != null) {
      messageStatus.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class StatusMessageStandardSchemeFactory implements SchemeFactory {
    public StatusMessageStandardScheme getScheme() {
      return new StatusMessageStandardScheme();
    }
  }

  private static class StatusMessageStandardScheme extends StandardScheme<StatusMessage> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, StatusMessage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MESSAGE_STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.messageStatus = new MessageStatus();
              struct.messageStatus.read(iprot);
              struct.setMessageStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BODY_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.bodyType = MessageBodyType.findByValue(iprot.readI32());
              struct.setBodyTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, StatusMessage struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.messageStatus != null) {
        oprot.writeFieldBegin(MESSAGE_STATUS_FIELD_DESC);
        struct.messageStatus.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.bodyType != null) {
        oprot.writeFieldBegin(BODY_TYPE_FIELD_DESC);
        oprot.writeI32(struct.bodyType.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class StatusMessageTupleSchemeFactory implements SchemeFactory {
    public StatusMessageTupleScheme getScheme() {
      return new StatusMessageTupleScheme();
    }
  }

  private static class StatusMessageTupleScheme extends TupleScheme<StatusMessage> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, StatusMessage struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.messageStatus.write(oprot);
      oprot.writeI32(struct.bodyType.getValue());
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, StatusMessage struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.messageStatus = new MessageStatus();
      struct.messageStatus.read(iprot);
      struct.setMessageStatusIsSet(true);
      struct.bodyType = MessageBodyType.findByValue(iprot.readI32());
      struct.setBodyTypeIsSet(true);
    }
  }

}

